name: proj_env
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - scikit-learn
  - pandas
  - pyyaml
  - keras
  - tensorflow
  - tqdm
  - pillow
  - pip
  - pip:
    - mlflow==3.10.1
    - Flask
    - python-dotenv
    - psutil
    - datasets
    - evaluate
    - accelerate
    - transformers
