name : "Financial-News-Analysis"
author : "Pranav Rao"
version : "v1"

topic:
  data:
    raw: "data/topic/raw"
    processed: "data/topic/processed"
    production: "data/topic/production"
    version: "v1"
  model:
    path:
    version: "v1"

sentiment:
  data:
    raw: "data/sentiment/raw"
    processed: "data/sentiment/processed"
    production: "data/sentiment/production"
    version: "v3"
    split_ratio:
      - 0.25
      - 0.25
    random_state: 42
  model:
    path:
    version: "v1"

deployment:
  logs:
  version:

post-production:
  logs:
