{
 "title": "Financial News Analysis v3",
 "description": "Dashboard for Financial News Analysis AI application metrics and Hardware metrics",
 "tags": [
  "finance",
  "ai",
  "image"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Health",
   "type": "stat",
   "description": "Promotheus for Application is Up",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"financial-analysis\"}"
    }
   ]
  },
  {
   "title": "Inference Latency",
   "type": "timeseries",
   "description": "Calculates the average inference latency (seconds) per image",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(app_inference_latency_seconds_sum[1m])) / sum by (mode) (rate(app_inference_latency_seconds_count[1m]))",
     "legendFormat": "{{mode}} mode latency"
    }
   ]
  },
  {
   "title": "System CPU Utilization",
   "type": "timeseries",
   "description": "Tracks host CPU usage",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "Total CPU Usage %"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "stat",
   "description": "Number of images currently to be processed",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_active_requests_current)"
    }
   ]
  },
  {
   "title": "System & App Memory Utilization",
   "type": "timeseries",
   "description": "Monitors available host memory",
   "gridPos": { "h": 7, "w": 10, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Total Host RAM Used"
    },
    { "expr": "app_model_memory_bytes", "legendFormat": "App RSS Memory (Model)" }
   ]
  },
  {
   "title": "Request vs. Exception Rate",
   "type": "timeseries",
   "description": "Total incoming requests vs Exceptions",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (increase(app_total_requests_total[1m]))",
     "legendFormat": "Requests ({{mode}})"
    },
    {
     "expr": "sum by (mode, error_type) (increase(app_total_errors_total[1m]))",
     "legendFormat": "Errors ({{mode}} - {{error_type}})"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "timeseries",
   "description": "Disk Read Latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "Written ({{device}})"
    }
   ]
  },
  {
   "title": "CPU Context Switch",
   "type": "timeseries",
   "description": "Context Switching per sec in CPU",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(node_context_switches_total[1m])",
     "legendFormat": "Switches / sec"
    },
    { "expr": "rate(node_intr_total[1m])", "legendFormat": "Interrupts / sec" }
   ]
  },
  {
   "title": "Data Drift",
   "type": "timeseries",
   "description": "Rate of Change of Data Distribution seen by the Sentiment model",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (class_name) (rate(sent_model_input_classes_total[5m]))",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "Current Topic Data Distribution (Pie Chart)",
   "type": "piechart",
   "description": "Cumulative distribution of the data among topic classes seen till now",
   "gridPos": { "h": 10, "w": 6, "x": 9, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (class_name) (topic_model_input_classes_total)",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "Current Sentiment Data Distribution (Pie Chart)",
   "type": "piechart",
   "description": "Cumulative distribution of the data among sentiment classes seen till now",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (class_name) (sent_model_input_classes_total)",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "Data Drift",
   "type": "timeseries",
   "description": "Rate of Change of Data Distribution seen by the Topic Model",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (class_name) (rate(topic_model_input_classes_total[5m]))",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "Sentiment Data Drift Distribution",
   "type": "barchart",
   "description": "Drift in the sentiment class distribution",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 32 },
   "targets": [
    {
     "expr": "sum by (class_name) (rate(sent_model_input_classes_total[1h])) / scalar(sum(rate(sent_model_input_classes_total[1h])))",
     "legendFormat": "{{class_name}}"
    },
    {
     "expr": "sent_model_baseline_class_distribution",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "Topic Data Drift Distribution",
   "type": "barchart",
   "description": "Drift in the topic class distribution",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 32 },
   "targets": [
    {
     "expr": "sum by (class_name) (rate(topic_model_input_classes_total[1h])) / scalar(sum(rate(topic_model_input_classes_total[1h])))",
     "legendFormat": "{{class_name}}"
    },
    {
     "expr": "topic_model_baseline_class_distribution",
     "legendFormat": "{{class_name}}"
    }
   ]
  },
  {
   "title": "Overall Sentiment PSI",
   "type": "stat",
   "description": "PSI across all classes in Sentiment Analysis",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((( (sum by (class_name) (rate(sent_model_input_classes_total[1h])) / scalar(sum(rate(sent_model_input_classes_total[1h])))) + 1e-5 )- ( model_baseline_class_distribution + 1e-5 )) * ln(( (sum by (class_name) (rate(topic_model_input_classes_total[1h])) / scalar(sum(rate(topic_model_input_classes_total[1h])))) + 1e-5 )/ ( sent_model_baseline_data_dist + 1e-5 )))"
    }
   ]
  },
  {
   "title": "Model Reliability",
   "type": "timeseries",
   "description": "How reliable are each of the models",
   "gridPos": { "h": 8, "w": 10, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (model_name) (rate(model_inference_status_total{status!=\"success\"}[5m]))/sum by (model_name) (rate(model_inference_status_total[5m]))) * 100",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Model Accuracy Decay",
   "type": "timeseries",
   "description": "Calculates the model accuracy decay with time",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (model_name) (rate(model_prediction_correctness_total{status=\"correct\"}[24h]))/sum by (model_name) (rate(model_feedback_received_total[24h]))",
     "legendFormat": "{{mode_name}}"
    }
   ]
  },
  {
   "title": "Overall Topic PSI",
   "type": "stat",
   "description": "PSI across all classes in Topic Modelling",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((( (sum by (class_name) (rate(topic_model_input_classes_total[1h])) / scalar(sum(rate(topic_model_input_classes_total[1h])))) + 1e-5 )- ( model_baseline_class_dist + 1e-5 )) * ln(( (sum by (class_name) (rate(topic_model_input_classes_total[1h])) / scalar(sum(rate(topic_model_input_classes_total[1h])))) + 1e-5 )/ ( model_baseline_class_dist + 1e-5 )))"
    }
   ]
  },
  {
   "title": "Recent Alert Events",
   "type": "table",
   "description": "Displays all active alerts handled by Alertmanager",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 48 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  }
 ]
}