apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Use the container name and internal port for the Docker bridge network
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false