route:
  group_by: ['alertname']
  group_wait: 10s
  receiver: 'web.hook'
  
  routes:
  - receiver: 'web.hook'
    repeat_interval: 1h
    group_interval: 5m
    
  - receiver: "retrain.hook"
    matchers:
    - alertname = SevereTopicModelDrift
    - trigger_retrain = "true"
  
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://alert_server:5002/'
      
  - name: 'retrain.hook'
    webhook_configs:
      - url: 'http://airflow:airflow@airflow-apiserver:8080/api/v1/dags/topic_model_retrain_pipeline/dagRuns'
        send_resolved: false

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    # Apply inhibition if the alertname is the same.
    equal: [alertname, dev, instance]