name : "Financial-News-Analysis"
author : "Pranav Rao"
version : "v1"

topic:
  data:
    raw: "data/topic/raw"
    processed: "data/topic/processed"
    production: "data/topic/production"
    version: "v3"
    mapping: "data/topic/mapping.json"
    dist: "data/topic/dist.csv"
    train_valid_split: 0.25
    random_state : 42
    embed_len: 128
    no_classes: 20
  model:
    device: "cuda"
    name: "distilbert/distilbert-base-uncased"
    path: "models/topic/v2"
    output: "output/v2"
    version: "v2"
    hyperparams:
      lr: 3e-5
      train_batch_size: 32
      eval_batch_size: 16
      epochs: 5
      wgt_decay: 0.01

sentiment:
  data:
    raw: "data/sentiment/raw"
    processed: "data/sentiment/processed"
    production: "data/sentiment/production"
    version: "v4"
    mapping: "data/sentiment/mapping.json"
    split_ratio:
      - 0.25
      - 0.25
    random_state: 42
    no_classes: 3
    embed_len: 128
  model:
    name: "distilbert-base-uncased"
    path: "models/sentiment/v1"
    version: "v1"
    hyperparams:
      lr: 3e-5
      train_batch_size: 32
      eval_batch_size: 16
      epochs: 10
      weight_decay: 0.01
      gradient_accumulation_steps: 8

deployment:
  port: 6969  # Flask
  serve: 5001  # mlflow serve
  mlflow: 5000
  logs:
  version: "v2"

monitoring:
  port:
    model: 8001 # model logging
    streamlit: 8501 # streamlit
    node: 9100  # node manager
    alert: 5002 # alert mail server
    alertmanager: 9093 # manage alerts and silences
    prometheus: 9090 # prometheus server
    grafana: 3000 # grafana dashboard
    redis: 6379
  current_version: "v2"

mail_alerts:
  sender_mail: ${EMAIL}
  receiver_mail: ${EMAIL}
  password: ${PASSWORD}

post-production:
  logs:
